version: "3.9"
services:
  redis:
    image: redis:latest
    restart: always
    privileged: true
    ports:
      - 6379:6379
    volumes:
      - ./data/redis/data:/data
      - ./redis/etc:/usr/local/etc/redis
    command: redis-server /usr/local/etc/redis/redis.conf
  nginx:
    image: nginx:latest
    restart: always
    privileged: true
    volumes:
      - ./nginx/etc/nginx:/etc/nginx
      - ./var/www:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
networks:
  mynet1:
    driver: overlay
    attachable: false
