[package]
name = "shape-app"
version = { workspace = true }
edition.workspace = true
license.workspace = true
authors.workspace = true



[dependencies]
log.workspace = true
serde_json.workspace = true
shape = { path = "../shape" }
