[package]
name = "hello_macro_application"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
hello_macro = { path = "../hello_macro" }
hello_macro_derive = { path = "../hello_macro_derive" }

