#ifndef ERRORCODE
#define ERRORCODE

enum enErrorCode
{
    ERROR_BASE = 100,
    ERROR_DB_INSERT_ADD_CONTACT,
    ERROR_DB_GET_CONTACT_CONVERSATION,
    ERROR_DB_INSERT_USER_OFFLLINE,
    ERROR_DB_INSERT_ADD_CONTACT_TRANSIT,
    ERROR_DB_UPDATE_ADD_CONTACT = 105,
    ERROR_PROTOBUF_PARSE_FAILURE,
    ERROR_USER_OFFLINE,
    ERROR_DB_INSERT_MSG_FAILURE,
    ERROR_DB_INSERT_CONVERSATION_FAILURE,
    ERROR_DB_GET_GROUP_MEMBER,
    ERROR_ADDCONTACT_RSP,
};



#endif // ERRORCODE

