[package]
name = "package_analyze"
version = { workspace = true }
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true
