// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: chat.proto

#ifndef PROTOBUF_chat_2eproto__INCLUDED
#define PROTOBUF_chat_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace MarsMsgChat {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_chat_2eproto();
void protobuf_InitDefaults_chat_2eproto();
void protobuf_AssignDesc_chat_2eproto();
void protobuf_ShutdownFile_chat_2eproto();

class PushRsp;
class SendMsgReq;
class SendMsgRsp;

// ===================================================================

class SendMsgReq : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MarsMsgChat.SendMsgReq) */ {
 public:
  SendMsgReq();
  virtual ~SendMsgReq();

  SendMsgReq(const SendMsgReq& from);

  inline SendMsgReq& operator=(const SendMsgReq& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMsgReq& default_instance();

  static const SendMsgReq* internal_default_instance();

  void Swap(SendMsgReq* other);

  // implements Message ----------------------------------------------

  inline SendMsgReq* New() const { return New(NULL); }

  SendMsgReq* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendMsgReq& from);
  void MergeFrom(const SendMsgReq& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SendMsgReq* other);
  void UnsafeMergeFrom(const SendMsgReq& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required string access_token = 1;
  bool has_access_token() const;
  void clear_access_token();
  static const int kAccessTokenFieldNumber = 1;
  const ::std::string& access_token() const;
  void set_access_token(const ::std::string& value);
  void set_access_token(const char* value);
  void set_access_token(const char* value, size_t size);
  ::std::string* mutable_access_token();
  ::std::string* release_access_token();
  void set_allocated_access_token(::std::string* access_token);

  // required string userfrom = 2;
  bool has_userfrom() const;
  void clear_userfrom();
  static const int kUserfromFieldNumber = 2;
  const ::std::string& userfrom() const;
  void set_userfrom(const ::std::string& value);
  void set_userfrom(const char* value);
  void set_userfrom(const char* value, size_t size);
  ::std::string* mutable_userfrom();
  ::std::string* release_userfrom();
  void set_allocated_userfrom(::std::string* userfrom);

  // required string userTo = 3;
  bool has_userto() const;
  void clear_userto();
  static const int kUserToFieldNumber = 3;
  const ::std::string& userto() const;
  void set_userto(const ::std::string& value);
  void set_userto(const char* value);
  void set_userto(const char* value, size_t size);
  ::std::string* mutable_userto();
  ::std::string* release_userto();
  void set_allocated_userto(::std::string* userto);

  // required string text = 4;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 4;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // required int32 msgtype = 5;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgtypeFieldNumber = 5;
  ::google::protobuf::int32 msgtype() const;
  void set_msgtype(::google::protobuf::int32 value);

  // required string headimage = 6;
  bool has_headimage() const;
  void clear_headimage();
  static const int kHeadimageFieldNumber = 6;
  const ::std::string& headimage() const;
  void set_headimage(const ::std::string& value);
  void set_headimage(const char* value);
  void set_headimage(const char* value, size_t size);
  ::std::string* mutable_headimage();
  ::std::string* release_headimage();
  void set_allocated_headimage(::std::string* headimage);

  // required string sendname = 7;
  bool has_sendname() const;
  void clear_sendname();
  static const int kSendnameFieldNumber = 7;
  const ::std::string& sendname() const;
  void set_sendname(const ::std::string& value);
  void set_sendname(const char* value);
  void set_sendname(const char* value, size_t size);
  ::std::string* mutable_sendname();
  ::std::string* release_sendname();
  void set_allocated_sendname(::std::string* sendname);

  // required string senduserid = 8;
  bool has_senduserid() const;
  void clear_senduserid();
  static const int kSenduseridFieldNumber = 8;
  const ::std::string& senduserid() const;
  void set_senduserid(const ::std::string& value);
  void set_senduserid(const char* value);
  void set_senduserid(const char* value, size_t size);
  ::std::string* mutable_senduserid();
  ::std::string* release_senduserid();
  void set_allocated_senduserid(::std::string* senduserid);

  // required string converstionid = 10;
  bool has_converstionid() const;
  void clear_converstionid();
  static const int kConverstionidFieldNumber = 10;
  const ::std::string& converstionid() const;
  void set_converstionid(const ::std::string& value);
  void set_converstionid(const char* value);
  void set_converstionid(const char* value, size_t size);
  ::std::string* mutable_converstionid();
  ::std::string* release_converstionid();
  void set_allocated_converstionid(::std::string* converstionid);

  // required int32 sendtype = 11;
  bool has_sendtype() const;
  void clear_sendtype();
  static const int kSendtypeFieldNumber = 11;
  ::google::protobuf::int32 sendtype() const;
  void set_sendtype(::google::protobuf::int32 value);

  // required int64 msguniqueid = 12;
  bool has_msguniqueid() const;
  void clear_msguniqueid();
  static const int kMsguniqueidFieldNumber = 12;
  ::google::protobuf::int64 msguniqueid() const;
  void set_msguniqueid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MarsMsgChat.SendMsgReq)
 private:
  inline void set_has_access_token();
  inline void clear_has_access_token();
  inline void set_has_userfrom();
  inline void clear_has_userfrom();
  inline void set_has_userto();
  inline void clear_has_userto();
  inline void set_has_text();
  inline void clear_has_text();
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_headimage();
  inline void clear_has_headimage();
  inline void set_has_sendname();
  inline void clear_has_sendname();
  inline void set_has_senduserid();
  inline void clear_has_senduserid();
  inline void set_has_converstionid();
  inline void clear_has_converstionid();
  inline void set_has_sendtype();
  inline void clear_has_sendtype();
  inline void set_has_msguniqueid();
  inline void clear_has_msguniqueid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr access_token_;
  ::google::protobuf::internal::ArenaStringPtr userfrom_;
  ::google::protobuf::internal::ArenaStringPtr userto_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::google::protobuf::internal::ArenaStringPtr headimage_;
  ::google::protobuf::internal::ArenaStringPtr sendname_;
  ::google::protobuf::internal::ArenaStringPtr senduserid_;
  ::google::protobuf::internal::ArenaStringPtr converstionid_;
  ::google::protobuf::int32 msgtype_;
  ::google::protobuf::int32 sendtype_;
  ::google::protobuf::int64 msguniqueid_;
  friend void  protobuf_InitDefaults_chat_2eproto_impl();
  friend void  protobuf_AddDesc_chat_2eproto_impl();
  friend void protobuf_AssignDesc_chat_2eproto();
  friend void protobuf_ShutdownFile_chat_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SendMsgReq> SendMsgReq_default_instance_;

// -------------------------------------------------------------------

class SendMsgRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MarsMsgChat.SendMsgRsp) */ {
 public:
  SendMsgRsp();
  virtual ~SendMsgRsp();

  SendMsgRsp(const SendMsgRsp& from);

  inline SendMsgRsp& operator=(const SendMsgRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const SendMsgRsp& default_instance();

  static const SendMsgRsp* internal_default_instance();

  void Swap(SendMsgRsp* other);

  // implements Message ----------------------------------------------

  inline SendMsgRsp* New() const { return New(NULL); }

  SendMsgRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const SendMsgRsp& from);
  void MergeFrom(const SendMsgRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(SendMsgRsp* other);
  void UnsafeMergeFrom(const SendMsgRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 err_code = 1;
  bool has_err_code() const;
  void clear_err_code();
  static const int kErrCodeFieldNumber = 1;
  ::google::protobuf::int32 err_code() const;
  void set_err_code(::google::protobuf::int32 value);

  // required int32 errmsg = 2;
  bool has_errmsg() const;
  void clear_errmsg();
  static const int kErrmsgFieldNumber = 2;
  ::google::protobuf::int32 errmsg() const;
  void set_errmsg(::google::protobuf::int32 value);

  // required int64 msgid = 3;
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgidFieldNumber = 3;
  ::google::protobuf::int64 msgid() const;
  void set_msgid(::google::protobuf::int64 value);

  // required string access_token = 4;
  bool has_access_token() const;
  void clear_access_token();
  static const int kAccessTokenFieldNumber = 4;
  const ::std::string& access_token() const;
  void set_access_token(const ::std::string& value);
  void set_access_token(const char* value);
  void set_access_token(const char* value, size_t size);
  ::std::string* mutable_access_token();
  ::std::string* release_access_token();
  void set_allocated_access_token(::std::string* access_token);

  // required string converstionid = 5;
  bool has_converstionid() const;
  void clear_converstionid();
  static const int kConverstionidFieldNumber = 5;
  const ::std::string& converstionid() const;
  void set_converstionid(const ::std::string& value);
  void set_converstionid(const char* value);
  void set_converstionid(const char* value, size_t size);
  ::std::string* mutable_converstionid();
  ::std::string* release_converstionid();
  void set_allocated_converstionid(::std::string* converstionid);

  // required int64 msguniqueid = 6;
  bool has_msguniqueid() const;
  void clear_msguniqueid();
  static const int kMsguniqueidFieldNumber = 6;
  ::google::protobuf::int64 msguniqueid() const;
  void set_msguniqueid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MarsMsgChat.SendMsgRsp)
 private:
  inline void set_has_err_code();
  inline void clear_has_err_code();
  inline void set_has_errmsg();
  inline void clear_has_errmsg();
  inline void set_has_msgid();
  inline void clear_has_msgid();
  inline void set_has_access_token();
  inline void clear_has_access_token();
  inline void set_has_converstionid();
  inline void clear_has_converstionid();
  inline void set_has_msguniqueid();
  inline void clear_has_msguniqueid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr access_token_;
  ::google::protobuf::internal::ArenaStringPtr converstionid_;
  ::google::protobuf::int32 err_code_;
  ::google::protobuf::int32 errmsg_;
  ::google::protobuf::int64 msgid_;
  ::google::protobuf::int64 msguniqueid_;
  friend void  protobuf_InitDefaults_chat_2eproto_impl();
  friend void  protobuf_AddDesc_chat_2eproto_impl();
  friend void protobuf_AssignDesc_chat_2eproto();
  friend void protobuf_ShutdownFile_chat_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<SendMsgRsp> SendMsgRsp_default_instance_;

// -------------------------------------------------------------------

class PushRsp : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MarsMsgChat.PushRsp) */ {
 public:
  PushRsp();
  virtual ~PushRsp();

  PushRsp(const PushRsp& from);

  inline PushRsp& operator=(const PushRsp& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const PushRsp& default_instance();

  static const PushRsp* internal_default_instance();

  void Swap(PushRsp* other);

  // implements Message ----------------------------------------------

  inline PushRsp* New() const { return New(NULL); }

  PushRsp* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const PushRsp& from);
  void MergeFrom(const PushRsp& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(PushRsp* other);
  void UnsafeMergeFrom(const PushRsp& from);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 msgpushtype = 1;
  bool has_msgpushtype() const;
  void clear_msgpushtype();
  static const int kMsgpushtypeFieldNumber = 1;
  ::google::protobuf::int32 msgpushtype() const;
  void set_msgpushtype(::google::protobuf::int32 value);

  // required int32 errmsg = 2;
  bool has_errmsg() const;
  void clear_errmsg();
  static const int kErrmsgFieldNumber = 2;
  ::google::protobuf::int32 errmsg() const;
  void set_errmsg(::google::protobuf::int32 value);

  // required int32 state = 3;
  bool has_state() const;
  void clear_state();
  static const int kStateFieldNumber = 3;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // required string accesstoken = 4;
  bool has_accesstoken() const;
  void clear_accesstoken();
  static const int kAccesstokenFieldNumber = 4;
  const ::std::string& accesstoken() const;
  void set_accesstoken(const ::std::string& value);
  void set_accesstoken(const char* value);
  void set_accesstoken(const char* value, size_t size);
  ::std::string* mutable_accesstoken();
  ::std::string* release_accesstoken();
  void set_allocated_accesstoken(::std::string* accesstoken);

  // required string userfrom = 5;
  bool has_userfrom() const;
  void clear_userfrom();
  static const int kUserfromFieldNumber = 5;
  const ::std::string& userfrom() const;
  void set_userfrom(const ::std::string& value);
  void set_userfrom(const char* value);
  void set_userfrom(const char* value, size_t size);
  ::std::string* mutable_userfrom();
  ::std::string* release_userfrom();
  void set_allocated_userfrom(::std::string* userfrom);

  // required string userto = 6;
  bool has_userto() const;
  void clear_userto();
  static const int kUsertoFieldNumber = 6;
  const ::std::string& userto() const;
  void set_userto(const ::std::string& value);
  void set_userto(const char* value);
  void set_userto(const char* value, size_t size);
  ::std::string* mutable_userto();
  ::std::string* release_userto();
  void set_allocated_userto(::std::string* userto);

  // required string text = 7;
  bool has_text() const;
  void clear_text();
  static const int kTextFieldNumber = 7;
  const ::std::string& text() const;
  void set_text(const ::std::string& value);
  void set_text(const char* value);
  void set_text(const char* value, size_t size);
  ::std::string* mutable_text();
  ::std::string* release_text();
  void set_allocated_text(::std::string* text);

  // required string headimage = 8;
  bool has_headimage() const;
  void clear_headimage();
  static const int kHeadimageFieldNumber = 8;
  const ::std::string& headimage() const;
  void set_headimage(const ::std::string& value);
  void set_headimage(const char* value);
  void set_headimage(const char* value, size_t size);
  ::std::string* mutable_headimage();
  ::std::string* release_headimage();
  void set_allocated_headimage(::std::string* headimage);

  // required string sendname = 9;
  bool has_sendname() const;
  void clear_sendname();
  static const int kSendnameFieldNumber = 9;
  const ::std::string& sendname() const;
  void set_sendname(const ::std::string& value);
  void set_sendname(const char* value);
  void set_sendname(const char* value, size_t size);
  ::std::string* mutable_sendname();
  ::std::string* release_sendname();
  void set_allocated_sendname(::std::string* sendname);

  // required string senduserid = 10;
  bool has_senduserid() const;
  void clear_senduserid();
  static const int kSenduseridFieldNumber = 10;
  const ::std::string& senduserid() const;
  void set_senduserid(const ::std::string& value);
  void set_senduserid(const char* value);
  void set_senduserid(const char* value, size_t size);
  ::std::string* mutable_senduserid();
  ::std::string* release_senduserid();
  void set_allocated_senduserid(::std::string* senduserid);

  // required string converstionid = 11;
  bool has_converstionid() const;
  void clear_converstionid();
  static const int kConverstionidFieldNumber = 11;
  const ::std::string& converstionid() const;
  void set_converstionid(const ::std::string& value);
  void set_converstionid(const char* value);
  void set_converstionid(const char* value, size_t size);
  ::std::string* mutable_converstionid();
  ::std::string* release_converstionid();
  void set_allocated_converstionid(::std::string* converstionid);

  // required int32 sendtype = 12;
  bool has_sendtype() const;
  void clear_sendtype();
  static const int kSendtypeFieldNumber = 12;
  ::google::protobuf::int32 sendtype() const;
  void set_sendtype(::google::protobuf::int32 value);

  // required int32 msgtype = 13;
  bool has_msgtype() const;
  void clear_msgtype();
  static const int kMsgtypeFieldNumber = 13;
  ::google::protobuf::int32 msgtype() const;
  void set_msgtype(::google::protobuf::int32 value);

  // required int64 msgid = 14;
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgidFieldNumber = 14;
  ::google::protobuf::int64 msgid() const;
  void set_msgid(::google::protobuf::int64 value);

  // @@protoc_insertion_point(class_scope:MarsMsgChat.PushRsp)
 private:
  inline void set_has_msgpushtype();
  inline void clear_has_msgpushtype();
  inline void set_has_errmsg();
  inline void clear_has_errmsg();
  inline void set_has_state();
  inline void clear_has_state();
  inline void set_has_accesstoken();
  inline void clear_has_accesstoken();
  inline void set_has_userfrom();
  inline void clear_has_userfrom();
  inline void set_has_userto();
  inline void clear_has_userto();
  inline void set_has_text();
  inline void clear_has_text();
  inline void set_has_headimage();
  inline void clear_has_headimage();
  inline void set_has_sendname();
  inline void clear_has_sendname();
  inline void set_has_senduserid();
  inline void clear_has_senduserid();
  inline void set_has_converstionid();
  inline void clear_has_converstionid();
  inline void set_has_sendtype();
  inline void clear_has_sendtype();
  inline void set_has_msgtype();
  inline void clear_has_msgtype();
  inline void set_has_msgid();
  inline void clear_has_msgid();

  // helper for ByteSizeLong()
  size_t RequiredFieldsByteSizeFallback() const;

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr accesstoken_;
  ::google::protobuf::internal::ArenaStringPtr userfrom_;
  ::google::protobuf::internal::ArenaStringPtr userto_;
  ::google::protobuf::internal::ArenaStringPtr text_;
  ::google::protobuf::internal::ArenaStringPtr headimage_;
  ::google::protobuf::internal::ArenaStringPtr sendname_;
  ::google::protobuf::internal::ArenaStringPtr senduserid_;
  ::google::protobuf::internal::ArenaStringPtr converstionid_;
  ::google::protobuf::int32 msgpushtype_;
  ::google::protobuf::int32 errmsg_;
  ::google::protobuf::int32 state_;
  ::google::protobuf::int32 sendtype_;
  ::google::protobuf::int64 msgid_;
  ::google::protobuf::int32 msgtype_;
  friend void  protobuf_InitDefaults_chat_2eproto_impl();
  friend void  protobuf_AddDesc_chat_2eproto_impl();
  friend void protobuf_AssignDesc_chat_2eproto();
  friend void protobuf_ShutdownFile_chat_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<PushRsp> PushRsp_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// SendMsgReq

// required string access_token = 1;
inline bool SendMsgReq::has_access_token() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMsgReq::set_has_access_token() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMsgReq::clear_has_access_token() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMsgReq::clear_access_token() {
  access_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_access_token();
}
inline const ::std::string& SendMsgReq::access_token() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.access_token)
  return access_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_access_token(const ::std::string& value) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.access_token)
}
inline void SendMsgReq::set_access_token(const char* value) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.access_token)
}
inline void SendMsgReq::set_access_token(const char* value, size_t size) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.access_token)
}
inline ::std::string* SendMsgReq::mutable_access_token() {
  set_has_access_token();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.access_token)
  return access_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_access_token() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.access_token)
  clear_has_access_token();
  return access_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_access_token(::std::string* access_token) {
  if (access_token != NULL) {
    set_has_access_token();
  } else {
    clear_has_access_token();
  }
  access_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_token);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.access_token)
}

// required string userfrom = 2;
inline bool SendMsgReq::has_userfrom() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendMsgReq::set_has_userfrom() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendMsgReq::clear_has_userfrom() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendMsgReq::clear_userfrom() {
  userfrom_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_userfrom();
}
inline const ::std::string& SendMsgReq::userfrom() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.userfrom)
  return userfrom_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_userfrom(const ::std::string& value) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.userfrom)
}
inline void SendMsgReq::set_userfrom(const char* value) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.userfrom)
}
inline void SendMsgReq::set_userfrom(const char* value, size_t size) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.userfrom)
}
inline ::std::string* SendMsgReq::mutable_userfrom() {
  set_has_userfrom();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.userfrom)
  return userfrom_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_userfrom() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.userfrom)
  clear_has_userfrom();
  return userfrom_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_userfrom(::std::string* userfrom) {
  if (userfrom != NULL) {
    set_has_userfrom();
  } else {
    clear_has_userfrom();
  }
  userfrom_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userfrom);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.userfrom)
}

// required string userTo = 3;
inline bool SendMsgReq::has_userto() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SendMsgReq::set_has_userto() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SendMsgReq::clear_has_userto() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SendMsgReq::clear_userto() {
  userto_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_userto();
}
inline const ::std::string& SendMsgReq::userto() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.userTo)
  return userto_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_userto(const ::std::string& value) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.userTo)
}
inline void SendMsgReq::set_userto(const char* value) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.userTo)
}
inline void SendMsgReq::set_userto(const char* value, size_t size) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.userTo)
}
inline ::std::string* SendMsgReq::mutable_userto() {
  set_has_userto();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.userTo)
  return userto_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_userto() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.userTo)
  clear_has_userto();
  return userto_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_userto(::std::string* userto) {
  if (userto != NULL) {
    set_has_userto();
  } else {
    clear_has_userto();
  }
  userto_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userto);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.userTo)
}

// required string text = 4;
inline bool SendMsgReq::has_text() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SendMsgReq::set_has_text() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SendMsgReq::clear_has_text() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SendMsgReq::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& SendMsgReq::text() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.text)
  return text_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.text)
}
inline void SendMsgReq::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.text)
}
inline void SendMsgReq::set_text(const char* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.text)
}
inline ::std::string* SendMsgReq::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_text() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.text)
}

// required int32 msgtype = 5;
inline bool SendMsgReq::has_msgtype() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SendMsgReq::set_has_msgtype() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SendMsgReq::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SendMsgReq::clear_msgtype() {
  msgtype_ = 0;
  clear_has_msgtype();
}
inline ::google::protobuf::int32 SendMsgReq::msgtype() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.msgtype)
  return msgtype_;
}
inline void SendMsgReq::set_msgtype(::google::protobuf::int32 value) {
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.msgtype)
}

// required string headimage = 6;
inline bool SendMsgReq::has_headimage() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SendMsgReq::set_has_headimage() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SendMsgReq::clear_has_headimage() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SendMsgReq::clear_headimage() {
  headimage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_headimage();
}
inline const ::std::string& SendMsgReq::headimage() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.headimage)
  return headimage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_headimage(const ::std::string& value) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.headimage)
}
inline void SendMsgReq::set_headimage(const char* value) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.headimage)
}
inline void SendMsgReq::set_headimage(const char* value, size_t size) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.headimage)
}
inline ::std::string* SendMsgReq::mutable_headimage() {
  set_has_headimage();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.headimage)
  return headimage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_headimage() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.headimage)
  clear_has_headimage();
  return headimage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_headimage(::std::string* headimage) {
  if (headimage != NULL) {
    set_has_headimage();
  } else {
    clear_has_headimage();
  }
  headimage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), headimage);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.headimage)
}

// required string sendname = 7;
inline bool SendMsgReq::has_sendname() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void SendMsgReq::set_has_sendname() {
  _has_bits_[0] |= 0x00000040u;
}
inline void SendMsgReq::clear_has_sendname() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void SendMsgReq::clear_sendname() {
  sendname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sendname();
}
inline const ::std::string& SendMsgReq::sendname() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.sendname)
  return sendname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_sendname(const ::std::string& value) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.sendname)
}
inline void SendMsgReq::set_sendname(const char* value) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.sendname)
}
inline void SendMsgReq::set_sendname(const char* value, size_t size) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.sendname)
}
inline ::std::string* SendMsgReq::mutable_sendname() {
  set_has_sendname();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.sendname)
  return sendname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_sendname() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.sendname)
  clear_has_sendname();
  return sendname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_sendname(::std::string* sendname) {
  if (sendname != NULL) {
    set_has_sendname();
  } else {
    clear_has_sendname();
  }
  sendname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sendname);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.sendname)
}

// required string senduserid = 8;
inline bool SendMsgReq::has_senduserid() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void SendMsgReq::set_has_senduserid() {
  _has_bits_[0] |= 0x00000080u;
}
inline void SendMsgReq::clear_has_senduserid() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void SendMsgReq::clear_senduserid() {
  senduserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_senduserid();
}
inline const ::std::string& SendMsgReq::senduserid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.senduserid)
  return senduserid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_senduserid(const ::std::string& value) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.senduserid)
}
inline void SendMsgReq::set_senduserid(const char* value) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.senduserid)
}
inline void SendMsgReq::set_senduserid(const char* value, size_t size) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.senduserid)
}
inline ::std::string* SendMsgReq::mutable_senduserid() {
  set_has_senduserid();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.senduserid)
  return senduserid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_senduserid() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.senduserid)
  clear_has_senduserid();
  return senduserid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_senduserid(::std::string* senduserid) {
  if (senduserid != NULL) {
    set_has_senduserid();
  } else {
    clear_has_senduserid();
  }
  senduserid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), senduserid);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.senduserid)
}

// required string converstionid = 10;
inline bool SendMsgReq::has_converstionid() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void SendMsgReq::set_has_converstionid() {
  _has_bits_[0] |= 0x00000100u;
}
inline void SendMsgReq::clear_has_converstionid() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void SendMsgReq::clear_converstionid() {
  converstionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_converstionid();
}
inline const ::std::string& SendMsgReq::converstionid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.converstionid)
  return converstionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_converstionid(const ::std::string& value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.converstionid)
}
inline void SendMsgReq::set_converstionid(const char* value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgReq.converstionid)
}
inline void SendMsgReq::set_converstionid(const char* value, size_t size) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgReq.converstionid)
}
inline ::std::string* SendMsgReq::mutable_converstionid() {
  set_has_converstionid();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgReq.converstionid)
  return converstionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgReq::release_converstionid() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgReq.converstionid)
  clear_has_converstionid();
  return converstionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgReq::set_allocated_converstionid(::std::string* converstionid) {
  if (converstionid != NULL) {
    set_has_converstionid();
  } else {
    clear_has_converstionid();
  }
  converstionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), converstionid);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgReq.converstionid)
}

// required int32 sendtype = 11;
inline bool SendMsgReq::has_sendtype() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void SendMsgReq::set_has_sendtype() {
  _has_bits_[0] |= 0x00000200u;
}
inline void SendMsgReq::clear_has_sendtype() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void SendMsgReq::clear_sendtype() {
  sendtype_ = 0;
  clear_has_sendtype();
}
inline ::google::protobuf::int32 SendMsgReq::sendtype() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.sendtype)
  return sendtype_;
}
inline void SendMsgReq::set_sendtype(::google::protobuf::int32 value) {
  set_has_sendtype();
  sendtype_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.sendtype)
}

// required int64 msguniqueid = 12;
inline bool SendMsgReq::has_msguniqueid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void SendMsgReq::set_has_msguniqueid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void SendMsgReq::clear_has_msguniqueid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void SendMsgReq::clear_msguniqueid() {
  msguniqueid_ = GOOGLE_LONGLONG(0);
  clear_has_msguniqueid();
}
inline ::google::protobuf::int64 SendMsgReq::msguniqueid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgReq.msguniqueid)
  return msguniqueid_;
}
inline void SendMsgReq::set_msguniqueid(::google::protobuf::int64 value) {
  set_has_msguniqueid();
  msguniqueid_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgReq.msguniqueid)
}

inline const SendMsgReq* SendMsgReq::internal_default_instance() {
  return &SendMsgReq_default_instance_.get();
}
// -------------------------------------------------------------------

// SendMsgRsp

// required int32 err_code = 1;
inline bool SendMsgRsp::has_err_code() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void SendMsgRsp::set_has_err_code() {
  _has_bits_[0] |= 0x00000001u;
}
inline void SendMsgRsp::clear_has_err_code() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void SendMsgRsp::clear_err_code() {
  err_code_ = 0;
  clear_has_err_code();
}
inline ::google::protobuf::int32 SendMsgRsp::err_code() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.err_code)
  return err_code_;
}
inline void SendMsgRsp::set_err_code(::google::protobuf::int32 value) {
  set_has_err_code();
  err_code_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.err_code)
}

// required int32 errmsg = 2;
inline bool SendMsgRsp::has_errmsg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void SendMsgRsp::set_has_errmsg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void SendMsgRsp::clear_has_errmsg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void SendMsgRsp::clear_errmsg() {
  errmsg_ = 0;
  clear_has_errmsg();
}
inline ::google::protobuf::int32 SendMsgRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.errmsg)
  return errmsg_;
}
inline void SendMsgRsp::set_errmsg(::google::protobuf::int32 value) {
  set_has_errmsg();
  errmsg_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.errmsg)
}

// required int64 msgid = 3;
inline bool SendMsgRsp::has_msgid() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void SendMsgRsp::set_has_msgid() {
  _has_bits_[0] |= 0x00000004u;
}
inline void SendMsgRsp::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void SendMsgRsp::clear_msgid() {
  msgid_ = GOOGLE_LONGLONG(0);
  clear_has_msgid();
}
inline ::google::protobuf::int64 SendMsgRsp::msgid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.msgid)
  return msgid_;
}
inline void SendMsgRsp::set_msgid(::google::protobuf::int64 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.msgid)
}

// required string access_token = 4;
inline bool SendMsgRsp::has_access_token() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void SendMsgRsp::set_has_access_token() {
  _has_bits_[0] |= 0x00000008u;
}
inline void SendMsgRsp::clear_has_access_token() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void SendMsgRsp::clear_access_token() {
  access_token_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_access_token();
}
inline const ::std::string& SendMsgRsp::access_token() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.access_token)
  return access_token_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgRsp::set_access_token(const ::std::string& value) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.access_token)
}
inline void SendMsgRsp::set_access_token(const char* value) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgRsp.access_token)
}
inline void SendMsgRsp::set_access_token(const char* value, size_t size) {
  set_has_access_token();
  access_token_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgRsp.access_token)
}
inline ::std::string* SendMsgRsp::mutable_access_token() {
  set_has_access_token();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgRsp.access_token)
  return access_token_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgRsp::release_access_token() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgRsp.access_token)
  clear_has_access_token();
  return access_token_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgRsp::set_allocated_access_token(::std::string* access_token) {
  if (access_token != NULL) {
    set_has_access_token();
  } else {
    clear_has_access_token();
  }
  access_token_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), access_token);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgRsp.access_token)
}

// required string converstionid = 5;
inline bool SendMsgRsp::has_converstionid() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void SendMsgRsp::set_has_converstionid() {
  _has_bits_[0] |= 0x00000010u;
}
inline void SendMsgRsp::clear_has_converstionid() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void SendMsgRsp::clear_converstionid() {
  converstionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_converstionid();
}
inline const ::std::string& SendMsgRsp::converstionid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.converstionid)
  return converstionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgRsp::set_converstionid(const ::std::string& value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.converstionid)
}
inline void SendMsgRsp::set_converstionid(const char* value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.SendMsgRsp.converstionid)
}
inline void SendMsgRsp::set_converstionid(const char* value, size_t size) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.SendMsgRsp.converstionid)
}
inline ::std::string* SendMsgRsp::mutable_converstionid() {
  set_has_converstionid();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.SendMsgRsp.converstionid)
  return converstionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SendMsgRsp::release_converstionid() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.SendMsgRsp.converstionid)
  clear_has_converstionid();
  return converstionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SendMsgRsp::set_allocated_converstionid(::std::string* converstionid) {
  if (converstionid != NULL) {
    set_has_converstionid();
  } else {
    clear_has_converstionid();
  }
  converstionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), converstionid);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.SendMsgRsp.converstionid)
}

// required int64 msguniqueid = 6;
inline bool SendMsgRsp::has_msguniqueid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void SendMsgRsp::set_has_msguniqueid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void SendMsgRsp::clear_has_msguniqueid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void SendMsgRsp::clear_msguniqueid() {
  msguniqueid_ = GOOGLE_LONGLONG(0);
  clear_has_msguniqueid();
}
inline ::google::protobuf::int64 SendMsgRsp::msguniqueid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.SendMsgRsp.msguniqueid)
  return msguniqueid_;
}
inline void SendMsgRsp::set_msguniqueid(::google::protobuf::int64 value) {
  set_has_msguniqueid();
  msguniqueid_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.SendMsgRsp.msguniqueid)
}

inline const SendMsgRsp* SendMsgRsp::internal_default_instance() {
  return &SendMsgRsp_default_instance_.get();
}
// -------------------------------------------------------------------

// PushRsp

// required int32 msgpushtype = 1;
inline bool PushRsp::has_msgpushtype() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void PushRsp::set_has_msgpushtype() {
  _has_bits_[0] |= 0x00000001u;
}
inline void PushRsp::clear_has_msgpushtype() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void PushRsp::clear_msgpushtype() {
  msgpushtype_ = 0;
  clear_has_msgpushtype();
}
inline ::google::protobuf::int32 PushRsp::msgpushtype() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.msgpushtype)
  return msgpushtype_;
}
inline void PushRsp::set_msgpushtype(::google::protobuf::int32 value) {
  set_has_msgpushtype();
  msgpushtype_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.msgpushtype)
}

// required int32 errmsg = 2;
inline bool PushRsp::has_errmsg() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void PushRsp::set_has_errmsg() {
  _has_bits_[0] |= 0x00000002u;
}
inline void PushRsp::clear_has_errmsg() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void PushRsp::clear_errmsg() {
  errmsg_ = 0;
  clear_has_errmsg();
}
inline ::google::protobuf::int32 PushRsp::errmsg() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.errmsg)
  return errmsg_;
}
inline void PushRsp::set_errmsg(::google::protobuf::int32 value) {
  set_has_errmsg();
  errmsg_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.errmsg)
}

// required int32 state = 3;
inline bool PushRsp::has_state() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void PushRsp::set_has_state() {
  _has_bits_[0] |= 0x00000004u;
}
inline void PushRsp::clear_has_state() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void PushRsp::clear_state() {
  state_ = 0;
  clear_has_state();
}
inline ::google::protobuf::int32 PushRsp::state() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.state)
  return state_;
}
inline void PushRsp::set_state(::google::protobuf::int32 value) {
  set_has_state();
  state_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.state)
}

// required string accesstoken = 4;
inline bool PushRsp::has_accesstoken() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void PushRsp::set_has_accesstoken() {
  _has_bits_[0] |= 0x00000008u;
}
inline void PushRsp::clear_has_accesstoken() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void PushRsp::clear_accesstoken() {
  accesstoken_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_accesstoken();
}
inline const ::std::string& PushRsp::accesstoken() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.accesstoken)
  return accesstoken_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_accesstoken(const ::std::string& value) {
  set_has_accesstoken();
  accesstoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.accesstoken)
}
inline void PushRsp::set_accesstoken(const char* value) {
  set_has_accesstoken();
  accesstoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.accesstoken)
}
inline void PushRsp::set_accesstoken(const char* value, size_t size) {
  set_has_accesstoken();
  accesstoken_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.accesstoken)
}
inline ::std::string* PushRsp::mutable_accesstoken() {
  set_has_accesstoken();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.accesstoken)
  return accesstoken_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_accesstoken() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.accesstoken)
  clear_has_accesstoken();
  return accesstoken_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_accesstoken(::std::string* accesstoken) {
  if (accesstoken != NULL) {
    set_has_accesstoken();
  } else {
    clear_has_accesstoken();
  }
  accesstoken_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), accesstoken);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.accesstoken)
}

// required string userfrom = 5;
inline bool PushRsp::has_userfrom() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void PushRsp::set_has_userfrom() {
  _has_bits_[0] |= 0x00000010u;
}
inline void PushRsp::clear_has_userfrom() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void PushRsp::clear_userfrom() {
  userfrom_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_userfrom();
}
inline const ::std::string& PushRsp::userfrom() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.userfrom)
  return userfrom_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_userfrom(const ::std::string& value) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.userfrom)
}
inline void PushRsp::set_userfrom(const char* value) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.userfrom)
}
inline void PushRsp::set_userfrom(const char* value, size_t size) {
  set_has_userfrom();
  userfrom_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.userfrom)
}
inline ::std::string* PushRsp::mutable_userfrom() {
  set_has_userfrom();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.userfrom)
  return userfrom_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_userfrom() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.userfrom)
  clear_has_userfrom();
  return userfrom_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_userfrom(::std::string* userfrom) {
  if (userfrom != NULL) {
    set_has_userfrom();
  } else {
    clear_has_userfrom();
  }
  userfrom_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userfrom);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.userfrom)
}

// required string userto = 6;
inline bool PushRsp::has_userto() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void PushRsp::set_has_userto() {
  _has_bits_[0] |= 0x00000020u;
}
inline void PushRsp::clear_has_userto() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void PushRsp::clear_userto() {
  userto_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_userto();
}
inline const ::std::string& PushRsp::userto() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.userto)
  return userto_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_userto(const ::std::string& value) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.userto)
}
inline void PushRsp::set_userto(const char* value) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.userto)
}
inline void PushRsp::set_userto(const char* value, size_t size) {
  set_has_userto();
  userto_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.userto)
}
inline ::std::string* PushRsp::mutable_userto() {
  set_has_userto();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.userto)
  return userto_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_userto() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.userto)
  clear_has_userto();
  return userto_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_userto(::std::string* userto) {
  if (userto != NULL) {
    set_has_userto();
  } else {
    clear_has_userto();
  }
  userto_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), userto);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.userto)
}

// required string text = 7;
inline bool PushRsp::has_text() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void PushRsp::set_has_text() {
  _has_bits_[0] |= 0x00000040u;
}
inline void PushRsp::clear_has_text() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void PushRsp::clear_text() {
  text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_text();
}
inline const ::std::string& PushRsp::text() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.text)
  return text_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_text(const ::std::string& value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.text)
}
inline void PushRsp::set_text(const char* value) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.text)
}
inline void PushRsp::set_text(const char* value, size_t size) {
  set_has_text();
  text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.text)
}
inline ::std::string* PushRsp::mutable_text() {
  set_has_text();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.text)
  return text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_text() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.text)
  clear_has_text();
  return text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_text(::std::string* text) {
  if (text != NULL) {
    set_has_text();
  } else {
    clear_has_text();
  }
  text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), text);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.text)
}

// required string headimage = 8;
inline bool PushRsp::has_headimage() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void PushRsp::set_has_headimage() {
  _has_bits_[0] |= 0x00000080u;
}
inline void PushRsp::clear_has_headimage() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void PushRsp::clear_headimage() {
  headimage_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_headimage();
}
inline const ::std::string& PushRsp::headimage() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.headimage)
  return headimage_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_headimage(const ::std::string& value) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.headimage)
}
inline void PushRsp::set_headimage(const char* value) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.headimage)
}
inline void PushRsp::set_headimage(const char* value, size_t size) {
  set_has_headimage();
  headimage_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.headimage)
}
inline ::std::string* PushRsp::mutable_headimage() {
  set_has_headimage();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.headimage)
  return headimage_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_headimage() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.headimage)
  clear_has_headimage();
  return headimage_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_headimage(::std::string* headimage) {
  if (headimage != NULL) {
    set_has_headimage();
  } else {
    clear_has_headimage();
  }
  headimage_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), headimage);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.headimage)
}

// required string sendname = 9;
inline bool PushRsp::has_sendname() const {
  return (_has_bits_[0] & 0x00000100u) != 0;
}
inline void PushRsp::set_has_sendname() {
  _has_bits_[0] |= 0x00000100u;
}
inline void PushRsp::clear_has_sendname() {
  _has_bits_[0] &= ~0x00000100u;
}
inline void PushRsp::clear_sendname() {
  sendname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_sendname();
}
inline const ::std::string& PushRsp::sendname() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.sendname)
  return sendname_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_sendname(const ::std::string& value) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.sendname)
}
inline void PushRsp::set_sendname(const char* value) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.sendname)
}
inline void PushRsp::set_sendname(const char* value, size_t size) {
  set_has_sendname();
  sendname_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.sendname)
}
inline ::std::string* PushRsp::mutable_sendname() {
  set_has_sendname();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.sendname)
  return sendname_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_sendname() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.sendname)
  clear_has_sendname();
  return sendname_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_sendname(::std::string* sendname) {
  if (sendname != NULL) {
    set_has_sendname();
  } else {
    clear_has_sendname();
  }
  sendname_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), sendname);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.sendname)
}

// required string senduserid = 10;
inline bool PushRsp::has_senduserid() const {
  return (_has_bits_[0] & 0x00000200u) != 0;
}
inline void PushRsp::set_has_senduserid() {
  _has_bits_[0] |= 0x00000200u;
}
inline void PushRsp::clear_has_senduserid() {
  _has_bits_[0] &= ~0x00000200u;
}
inline void PushRsp::clear_senduserid() {
  senduserid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_senduserid();
}
inline const ::std::string& PushRsp::senduserid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.senduserid)
  return senduserid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_senduserid(const ::std::string& value) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.senduserid)
}
inline void PushRsp::set_senduserid(const char* value) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.senduserid)
}
inline void PushRsp::set_senduserid(const char* value, size_t size) {
  set_has_senduserid();
  senduserid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.senduserid)
}
inline ::std::string* PushRsp::mutable_senduserid() {
  set_has_senduserid();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.senduserid)
  return senduserid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_senduserid() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.senduserid)
  clear_has_senduserid();
  return senduserid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_senduserid(::std::string* senduserid) {
  if (senduserid != NULL) {
    set_has_senduserid();
  } else {
    clear_has_senduserid();
  }
  senduserid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), senduserid);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.senduserid)
}

// required string converstionid = 11;
inline bool PushRsp::has_converstionid() const {
  return (_has_bits_[0] & 0x00000400u) != 0;
}
inline void PushRsp::set_has_converstionid() {
  _has_bits_[0] |= 0x00000400u;
}
inline void PushRsp::clear_has_converstionid() {
  _has_bits_[0] &= ~0x00000400u;
}
inline void PushRsp::clear_converstionid() {
  converstionid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_converstionid();
}
inline const ::std::string& PushRsp::converstionid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.converstionid)
  return converstionid_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_converstionid(const ::std::string& value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.converstionid)
}
inline void PushRsp::set_converstionid(const char* value) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsMsgChat.PushRsp.converstionid)
}
inline void PushRsp::set_converstionid(const char* value, size_t size) {
  set_has_converstionid();
  converstionid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsMsgChat.PushRsp.converstionid)
}
inline ::std::string* PushRsp::mutable_converstionid() {
  set_has_converstionid();
  // @@protoc_insertion_point(field_mutable:MarsMsgChat.PushRsp.converstionid)
  return converstionid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* PushRsp::release_converstionid() {
  // @@protoc_insertion_point(field_release:MarsMsgChat.PushRsp.converstionid)
  clear_has_converstionid();
  return converstionid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void PushRsp::set_allocated_converstionid(::std::string* converstionid) {
  if (converstionid != NULL) {
    set_has_converstionid();
  } else {
    clear_has_converstionid();
  }
  converstionid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), converstionid);
  // @@protoc_insertion_point(field_set_allocated:MarsMsgChat.PushRsp.converstionid)
}

// required int32 sendtype = 12;
inline bool PushRsp::has_sendtype() const {
  return (_has_bits_[0] & 0x00000800u) != 0;
}
inline void PushRsp::set_has_sendtype() {
  _has_bits_[0] |= 0x00000800u;
}
inline void PushRsp::clear_has_sendtype() {
  _has_bits_[0] &= ~0x00000800u;
}
inline void PushRsp::clear_sendtype() {
  sendtype_ = 0;
  clear_has_sendtype();
}
inline ::google::protobuf::int32 PushRsp::sendtype() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.sendtype)
  return sendtype_;
}
inline void PushRsp::set_sendtype(::google::protobuf::int32 value) {
  set_has_sendtype();
  sendtype_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.sendtype)
}

// required int32 msgtype = 13;
inline bool PushRsp::has_msgtype() const {
  return (_has_bits_[0] & 0x00001000u) != 0;
}
inline void PushRsp::set_has_msgtype() {
  _has_bits_[0] |= 0x00001000u;
}
inline void PushRsp::clear_has_msgtype() {
  _has_bits_[0] &= ~0x00001000u;
}
inline void PushRsp::clear_msgtype() {
  msgtype_ = 0;
  clear_has_msgtype();
}
inline ::google::protobuf::int32 PushRsp::msgtype() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.msgtype)
  return msgtype_;
}
inline void PushRsp::set_msgtype(::google::protobuf::int32 value) {
  set_has_msgtype();
  msgtype_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.msgtype)
}

// required int64 msgid = 14;
inline bool PushRsp::has_msgid() const {
  return (_has_bits_[0] & 0x00002000u) != 0;
}
inline void PushRsp::set_has_msgid() {
  _has_bits_[0] |= 0x00002000u;
}
inline void PushRsp::clear_has_msgid() {
  _has_bits_[0] &= ~0x00002000u;
}
inline void PushRsp::clear_msgid() {
  msgid_ = GOOGLE_LONGLONG(0);
  clear_has_msgid();
}
inline ::google::protobuf::int64 PushRsp::msgid() const {
  // @@protoc_insertion_point(field_get:MarsMsgChat.PushRsp.msgid)
  return msgid_;
}
inline void PushRsp::set_msgid(::google::protobuf::int64 value) {
  set_has_msgid();
  msgid_ = value;
  // @@protoc_insertion_point(field_set:MarsMsgChat.PushRsp.msgid)
}

inline const PushRsp* PushRsp::internal_default_instance() {
  return &PushRsp_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace MarsMsgChat

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_chat_2eproto__INCLUDED
