// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "login.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace MarsLogin {

namespace {

const ::google::protobuf::Descriptor* LoginRequst_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoginRequst_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_login_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_login_2eproto() {
  protobuf_AddDesc_login_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "login.proto");
  GOOGLE_CHECK(file != NULL);
  LoginRequst_descriptor_ = file->message_type(0);
  static const int LoginRequst_offsets_[7] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, username_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, userid_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, email_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, telphone_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, password_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, imagepath_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, custionjson_),
  };
  LoginRequst_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoginRequst_descriptor_,
      LoginRequst::internal_default_instance(),
      LoginRequst_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoginRequst),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoginRequst, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_login_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoginRequst_descriptor_, LoginRequst::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_login_2eproto() {
  LoginRequst_default_instance_.Shutdown();
  delete LoginRequst_reflection_;
}

void protobuf_InitDefaults_login_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::internal::GetEmptyString();
  LoginRequst_default_instance_.DefaultConstruct();
  LoginRequst_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_login_2eproto_once_);
void protobuf_InitDefaults_login_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_login_2eproto_once_,
                 &protobuf_InitDefaults_login_2eproto_impl);
}
void protobuf_AddDesc_login_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_login_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\013login.proto\022\tMarsLogin\"\212\001\n\013LoginRequst"
    "\022\020\n\010userName\030\001 \001(\t\022\016\n\006userID\030\002 \001(\005\022\r\n\005em"
    "ail\030\003 \001(\t\022\020\n\010telPhone\030\004 \001(\t\022\020\n\010password\030"
    "\005 \001(\t\022\021\n\timagePath\030\006 \001(\t\022\023\n\013CustionJson\030"
    "\007 \001(\tb\006proto3", 173);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "login.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_login_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_login_2eproto_once_);
void protobuf_AddDesc_login_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_login_2eproto_once_,
                 &protobuf_AddDesc_login_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_login_2eproto {
  StaticDescriptorInitializer_login_2eproto() {
    protobuf_AddDesc_login_2eproto();
  }
} static_descriptor_initializer_login_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoginRequst::kUserNameFieldNumber;
const int LoginRequst::kUserIDFieldNumber;
const int LoginRequst::kEmailFieldNumber;
const int LoginRequst::kTelPhoneFieldNumber;
const int LoginRequst::kPasswordFieldNumber;
const int LoginRequst::kImagePathFieldNumber;
const int LoginRequst::kCustionJsonFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoginRequst::LoginRequst()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_login_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:MarsLogin.LoginRequst)
}

void LoginRequst::InitAsDefaultInstance() {
}

LoginRequst::LoginRequst(const LoginRequst& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:MarsLogin.LoginRequst)
}

void LoginRequst::SharedCtor() {
  username_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  telphone_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  imagepath_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  custionjson_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  userid_ = 0;
  _cached_size_ = 0;
}

LoginRequst::~LoginRequst() {
  // @@protoc_insertion_point(destructor:MarsLogin.LoginRequst)
  SharedDtor();
}

void LoginRequst::SharedDtor() {
  username_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  email_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  telphone_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  imagepath_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  custionjson_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LoginRequst::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoginRequst::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoginRequst_descriptor_;
}

const LoginRequst& LoginRequst::default_instance() {
  protobuf_InitDefaults_login_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<LoginRequst> LoginRequst_default_instance_;

LoginRequst* LoginRequst::New(::google::protobuf::Arena* arena) const {
  LoginRequst* n = new LoginRequst;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoginRequst::Clear() {
// @@protoc_insertion_point(message_clear_start:MarsLogin.LoginRequst)
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  userid_ = 0;
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  telphone_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  imagepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  custionjson_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool LoginRequst::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MarsLogin.LoginRequst)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string userName = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_username()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->username().data(), this->username().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.userName"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_userID;
        break;
      }

      // optional int32 userID = 2;
      case 2: {
        if (tag == 16) {
         parse_userID:

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &userid_)));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_email;
        break;
      }

      // optional string email = 3;
      case 3: {
        if (tag == 26) {
         parse_email:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_email()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->email().data(), this->email().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.email"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(34)) goto parse_telPhone;
        break;
      }

      // optional string telPhone = 4;
      case 4: {
        if (tag == 34) {
         parse_telPhone:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_telphone()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->telphone().data(), this->telphone().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.telPhone"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_password;
        break;
      }

      // optional string password = 5;
      case 5: {
        if (tag == 42) {
         parse_password:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_password()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->password().data(), this->password().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.password"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(50)) goto parse_imagePath;
        break;
      }

      // optional string imagePath = 6;
      case 6: {
        if (tag == 50) {
         parse_imagePath:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_imagepath()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->imagepath().data(), this->imagepath().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.imagePath"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(58)) goto parse_CustionJson;
        break;
      }

      // optional string CustionJson = 7;
      case 7: {
        if (tag == 58) {
         parse_CustionJson:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_custionjson()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->custionjson().data(), this->custionjson().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "MarsLogin.LoginRequst.CustionJson"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MarsLogin.LoginRequst)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MarsLogin.LoginRequst)
  return false;
#undef DO_
}

void LoginRequst::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MarsLogin.LoginRequst)
  // optional string userName = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.userName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->username(), output);
  }

  // optional int32 userID = 2;
  if (this->userid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->userid(), output);
  }

  // optional string email = 3;
  if (this->email().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->email().data(), this->email().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.email");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->email(), output);
  }

  // optional string telPhone = 4;
  if (this->telphone().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->telphone().data(), this->telphone().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.telPhone");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->telphone(), output);
  }

  // optional string password = 5;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.password");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->password(), output);
  }

  // optional string imagePath = 6;
  if (this->imagepath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->imagepath().data(), this->imagepath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.imagePath");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->imagepath(), output);
  }

  // optional string CustionJson = 7;
  if (this->custionjson().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->custionjson().data(), this->custionjson().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.CustionJson");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->custionjson(), output);
  }

  // @@protoc_insertion_point(serialize_end:MarsLogin.LoginRequst)
}

::google::protobuf::uint8* LoginRequst::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MarsLogin.LoginRequst)
  // optional string userName = 1;
  if (this->username().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->username().data(), this->username().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.userName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->username(), target);
  }

  // optional int32 userID = 2;
  if (this->userid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->userid(), target);
  }

  // optional string email = 3;
  if (this->email().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->email().data(), this->email().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.email");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->email(), target);
  }

  // optional string telPhone = 4;
  if (this->telphone().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->telphone().data(), this->telphone().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.telPhone");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->telphone(), target);
  }

  // optional string password = 5;
  if (this->password().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->password().data(), this->password().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.password");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->password(), target);
  }

  // optional string imagePath = 6;
  if (this->imagepath().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->imagepath().data(), this->imagepath().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.imagePath");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->imagepath(), target);
  }

  // optional string CustionJson = 7;
  if (this->custionjson().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->custionjson().data(), this->custionjson().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "MarsLogin.LoginRequst.CustionJson");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->custionjson(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:MarsLogin.LoginRequst)
  return target;
}

size_t LoginRequst::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MarsLogin.LoginRequst)
  size_t total_size = 0;

  // optional string userName = 1;
  if (this->username().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->username());
  }

  // optional int32 userID = 2;
  if (this->userid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->userid());
  }

  // optional string email = 3;
  if (this->email().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->email());
  }

  // optional string telPhone = 4;
  if (this->telphone().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->telphone());
  }

  // optional string password = 5;
  if (this->password().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->password());
  }

  // optional string imagePath = 6;
  if (this->imagepath().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->imagepath());
  }

  // optional string CustionJson = 7;
  if (this->custionjson().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->custionjson());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoginRequst::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MarsLogin.LoginRequst)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const LoginRequst* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LoginRequst>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MarsLogin.LoginRequst)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MarsLogin.LoginRequst)
    UnsafeMergeFrom(*source);
  }
}

void LoginRequst::MergeFrom(const LoginRequst& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MarsLogin.LoginRequst)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void LoginRequst::UnsafeMergeFrom(const LoginRequst& from) {
  GOOGLE_DCHECK(&from != this);
  if (from.username().size() > 0) {

    username_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.username_);
  }
  if (from.userid() != 0) {
    set_userid(from.userid());
  }
  if (from.email().size() > 0) {

    email_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.email_);
  }
  if (from.telphone().size() > 0) {

    telphone_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.telphone_);
  }
  if (from.password().size() > 0) {

    password_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.password_);
  }
  if (from.imagepath().size() > 0) {

    imagepath_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.imagepath_);
  }
  if (from.custionjson().size() > 0) {

    custionjson_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.custionjson_);
  }
}

void LoginRequst::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MarsLogin.LoginRequst)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoginRequst::CopyFrom(const LoginRequst& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MarsLogin.LoginRequst)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool LoginRequst::IsInitialized() const {

  return true;
}

void LoginRequst::Swap(LoginRequst* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoginRequst::InternalSwap(LoginRequst* other) {
  username_.Swap(&other->username_);
  std::swap(userid_, other->userid_);
  email_.Swap(&other->email_);
  telphone_.Swap(&other->telphone_);
  password_.Swap(&other->password_);
  imagepath_.Swap(&other->imagepath_);
  custionjson_.Swap(&other->custionjson_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoginRequst::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoginRequst_descriptor_;
  metadata.reflection = LoginRequst_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoginRequst

// optional string userName = 1;
void LoginRequst::clear_username() {
  username_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::username() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.userName)
  return username_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_username(const ::std::string& value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.userName)
}
void LoginRequst::set_username(const char* value) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.userName)
}
void LoginRequst::set_username(const char* value, size_t size) {
  
  username_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.userName)
}
::std::string* LoginRequst::mutable_username() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.userName)
  return username_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_username() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.userName)
  
  return username_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_username(::std::string* username) {
  if (username != NULL) {
    
  } else {
    
  }
  username_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), username);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.userName)
}

// optional int32 userID = 2;
void LoginRequst::clear_userid() {
  userid_ = 0;
}
::google::protobuf::int32 LoginRequst::userid() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.userID)
  return userid_;
}
void LoginRequst::set_userid(::google::protobuf::int32 value) {
  
  userid_ = value;
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.userID)
}

// optional string email = 3;
void LoginRequst::clear_email() {
  email_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::email() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.email)
  return email_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_email(const ::std::string& value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.email)
}
void LoginRequst::set_email(const char* value) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.email)
}
void LoginRequst::set_email(const char* value, size_t size) {
  
  email_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.email)
}
::std::string* LoginRequst::mutable_email() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.email)
  return email_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_email() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.email)
  
  return email_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_email(::std::string* email) {
  if (email != NULL) {
    
  } else {
    
  }
  email_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), email);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.email)
}

// optional string telPhone = 4;
void LoginRequst::clear_telphone() {
  telphone_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::telphone() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.telPhone)
  return telphone_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_telphone(const ::std::string& value) {
  
  telphone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.telPhone)
}
void LoginRequst::set_telphone(const char* value) {
  
  telphone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.telPhone)
}
void LoginRequst::set_telphone(const char* value, size_t size) {
  
  telphone_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.telPhone)
}
::std::string* LoginRequst::mutable_telphone() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.telPhone)
  return telphone_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_telphone() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.telPhone)
  
  return telphone_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_telphone(::std::string* telphone) {
  if (telphone != NULL) {
    
  } else {
    
  }
  telphone_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), telphone);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.telPhone)
}

// optional string password = 5;
void LoginRequst::clear_password() {
  password_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::password() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.password)
  return password_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_password(const ::std::string& value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.password)
}
void LoginRequst::set_password(const char* value) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.password)
}
void LoginRequst::set_password(const char* value, size_t size) {
  
  password_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.password)
}
::std::string* LoginRequst::mutable_password() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.password)
  return password_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_password() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.password)
  
  return password_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_password(::std::string* password) {
  if (password != NULL) {
    
  } else {
    
  }
  password_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), password);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.password)
}

// optional string imagePath = 6;
void LoginRequst::clear_imagepath() {
  imagepath_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::imagepath() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.imagePath)
  return imagepath_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_imagepath(const ::std::string& value) {
  
  imagepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.imagePath)
}
void LoginRequst::set_imagepath(const char* value) {
  
  imagepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.imagePath)
}
void LoginRequst::set_imagepath(const char* value, size_t size) {
  
  imagepath_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.imagePath)
}
::std::string* LoginRequst::mutable_imagepath() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.imagePath)
  return imagepath_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_imagepath() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.imagePath)
  
  return imagepath_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_imagepath(::std::string* imagepath) {
  if (imagepath != NULL) {
    
  } else {
    
  }
  imagepath_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), imagepath);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.imagePath)
}

// optional string CustionJson = 7;
void LoginRequst::clear_custionjson() {
  custionjson_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
const ::std::string& LoginRequst::custionjson() const {
  // @@protoc_insertion_point(field_get:MarsLogin.LoginRequst.CustionJson)
  return custionjson_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_custionjson(const ::std::string& value) {
  
  custionjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:MarsLogin.LoginRequst.CustionJson)
}
void LoginRequst::set_custionjson(const char* value) {
  
  custionjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:MarsLogin.LoginRequst.CustionJson)
}
void LoginRequst::set_custionjson(const char* value, size_t size) {
  
  custionjson_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:MarsLogin.LoginRequst.CustionJson)
}
::std::string* LoginRequst::mutable_custionjson() {
  
  // @@protoc_insertion_point(field_mutable:MarsLogin.LoginRequst.CustionJson)
  return custionjson_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
::std::string* LoginRequst::release_custionjson() {
  // @@protoc_insertion_point(field_release:MarsLogin.LoginRequst.CustionJson)
  
  return custionjson_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
void LoginRequst::set_allocated_custionjson(::std::string* custionjson) {
  if (custionjson != NULL) {
    
  } else {
    
  }
  custionjson_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), custionjson);
  // @@protoc_insertion_point(field_set_allocated:MarsLogin.LoginRequst.CustionJson)
}

inline const LoginRequst* LoginRequst::internal_default_instance() {
  return &LoginRequst_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace MarsLogin

// @@protoc_insertion_point(global_scope)
